### ISSUE TITLE
Keyword "Execute Sql From File" does not work with multi-line SQL

### ISSUE THREAD

**Issue by hleskien** [Hi-Fi/robotframework-dblibrary#17]
Hi,

the keyword "Execute Sql From File" does not work with multi-line SQL because the method concatenates the lines without putting a space in between.

Kind regards,

Holger

**Comment by hleskien** [comment]
We found another bug:
```
-- Comment.
INSERT INTO
```
becomes

`-- Comment. INSERT INTO
`

I'll write another fix.

**Comment by Hi-Fi** [comment]
Fixes release with version 3.1.2. 

Thank you for these fixes.
